# Don't print a new line at the start of the prompt
add_newline = true

# Replace the "â¯" symbol in the prompt with "âœ"
[character]      # The name of the module we are configuring is "character"
#success_symbol = "[\\$](green)"     # The "symbol" segment is being set to "âœ"
#error_symbol = "[\\$](bold red)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[aws]
style = "bold blue"
symbol = "ğŸ…° "
disabled = true

[directory]
truncation_length = 8
truncate_to_repo = false
style = "bold white"

[kubernetes]
disabled=true

[kubernetes.context_aliases]
"arn:aws:eks:us-east-1:042293964381:cluster/aslicensing-test-1" = "ASLicensing - Dev"
